### ISSUE TITLE
Tanto slice graph gets messed on up function is really big

### ISSUE THREAD

**Issue by elbiazo** [Vector35/tanto#2]
First of all, really really useful plugin when you are reversing big binary!

Can't share the binary but whenever graph is really big, it would mess up the graph. Not sure if it is graphing api issue or tanto issue. I beleive this happened for `add slice` but it might also happen for `add block` I will try to look for binary that I can reproduce with later.

**Comment by KyleMiles** [comment]
When you say "messed up," what exactly do you mean? Basic blocks being rearranged (possibly strangely)? Dangling blocks at the top of the function? Weird edge routing?

Please check out [#58](https://github.com/Vector35/binaryninja-api/issues/58) and [#2551](https://github.com/Vector35/binaryninja-api/issues/2551) on the main repo to make sure it isn't either one of those, please.

**Comment by elbiazo** [comment]
i think it might be #58. Closing it now
